#pragma once
// Diagrams of the 32 DX7 algorithms (generated by tools/gen_dx7.py).
#include <stdint.h>
#include "core/dx7.h"

#ifdef __cplusplus
extern "C" {
#endif

#define DX7_ALGO_W   61     // diagram size in pixels
#define DX7_ALGO_H   49
#define DX7_ALGO_BOX 9      // operator box size

typedef struct {
    const uint8_t *bits;                 // DX7_ALGO_H rows of 8 bytes, MSB = leftmost pixel
    uint8_t opx[DX7_OPS], opy[DX7_OPS];  // top-left corner of each operator box (index 0 = operator 1)
} dx7_algo_gfx_t;

extern const dx7_algo_gfx_t dx7_algo_gfx[DX7_ALGORITHMS];   // index = algorithm - 1

#ifdef __cplusplus
}
#endif
