#pragma once
// GENERATED by tools/gen_ui_sprites.py from assets/UI_Sprites/ -- do not edit by hand (the format: assets/UI_Sprites/README.md).
#include "core/gui.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const gui_sprite_t spr8_ui_xy;

// The sprite of an image by its path without .png and frame number ("24/mod_osc"); NULL when there is no such image (the caller then
// draws its own fallback, so the art can arrive one file at a time).
const gui_sprite_t *ui_sprite(const char *name);

#ifdef __cplusplus
}
#endif
