#pragma once
// GENERATED by tools/gen_ui_sprites.py from assets/UI_Sprites/ -- do not edit by hand (the format: assets/UI_Sprites/README.md).
#include "core/gui.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const gui_sprite_t spr8_ui_cog;
extern const gui_sprite_t spr8_ui_xy;
extern const gui_sprite_t spr16_tab_algorithm;
extern const gui_sprite_t spr16_tab_curves;
extern const gui_sprite_t spr16_tab_envelope;
extern const gui_sprite_t spr16_tab_fx;
extern const gui_sprite_t spr16_tab_general;
extern const gui_sprite_t spr16_tab_joy;
extern const gui_sprite_t spr16_tab_keys;
extern const gui_sprite_t spr16_tab_leds;
extern const gui_sprite_t spr16_tab_macros;
extern const gui_sprite_t spr16_tab_modifiers;
extern const gui_sprite_t spr16_tab_operator;
extern const gui_sprite_t spr16_tab_rack;
extern const gui_sprite_t spr16_tab_samples;
extern const gui_sprite_t spr24_mod_comb;
extern const gui_sprite_t spr24_mod_eg;
extern const gui_sprite_t spr24_mod_env;
extern const gui_sprite_t spr24_mod_filter;
extern const gui_sprite_t spr24_mod_lfo;
extern const gui_sprite_t spr24_mod_mseq;
extern const gui_sprite_t spr24_mod_osc;
extern const gui_sprite_t spr24_mod_sampler;
extern const gui_sprite_t spr24_mod_sat;
extern const gui_sprite_t spr24_osc_3ring;
extern const gui_sprite_t spr24_osc_3saw;
extern const gui_sprite_t spr24_osc_3sine;
extern const gui_sprite_t spr24_osc_3sq;
extern const gui_sprite_t spr24_osc_3tri;
extern const gui_sprite_t spr24_osc_add;
extern const gui_sprite_t spr24_osc_bsnare;
extern const gui_sprite_t spr24_osc_buzz;
extern const gui_sprite_t spr24_osc_chaos;
extern const gui_sprite_t spr24_osc_chip;
extern const gui_sprite_t spr24_osc_clock;
extern const gui_sprite_t spr24_osc_cloud;
extern const gui_sprite_t spr24_osc_csaw;
extern const gui_sprite_t spr24_osc_cymbal;
extern const gui_sprite_t spr24_osc_digmod;
extern const gui_sprite_t spr24_osc_dust;
extern const gui_sprite_t spr24_osc_fbfm;
extern const gui_sprite_t spr24_osc_fm2;
extern const gui_sprite_t spr24_osc_fnoise;
extern const gui_sprite_t spr24_osc_fold;
extern const gui_sprite_t spr24_osc_grain;
extern const gui_sprite_t spr24_osc_karp;
extern const gui_sprite_t spr24_osc_kick;
extern const gui_sprite_t spr24_osc_modal;
extern const gui_sprite_t spr24_osc_morph;
extern const gui_sprite_t spr24_osc_morse;
extern const gui_sprite_t spr24_osc_noise;
extern const gui_sprite_t spr24_osc_pbass;
extern const gui_sprite_t spr24_osc_pbasss;
extern const gui_sprite_t spr24_osc_phat;
extern const gui_sprite_t spr24_osc_phat2;
extern const gui_sprite_t spr24_osc_phdist;
extern const gui_sprite_t spr24_osc_pnoise;
extern const gui_sprite_t spr24_osc_psnare;
extern const gui_sprite_t spr24_osc_psnrs;
extern const gui_sprite_t spr24_osc_pulse;
extern const gui_sprite_t spr24_osc_sawdn;
extern const gui_sprite_t spr24_osc_sawsq;
extern const gui_sprite_t spr24_osc_sawsub;
extern const gui_sprite_t spr24_osc_sawup;
extern const gui_sprite_t spr24_osc_sine;
extern const gui_sprite_t spr24_osc_sintri;
extern const gui_sprite_t spr24_osc_sqsub;
extern const gui_sprite_t spr24_osc_sqsync;
extern const gui_sprite_t spr24_osc_ssaw;
extern const gui_sprite_t spr24_osc_strng;
extern const gui_sprite_t spr24_osc_swsync;
extern const gui_sprite_t spr24_osc_terrn;
extern const gui_sprite_t spr24_osc_toy;
extern const gui_sprite_t spr24_osc_tri;
extern const gui_sprite_t spr24_osc_twin;
extern const gui_sprite_t spr24_osc_va;
extern const gui_sprite_t spr24_osc_vavcf;
extern const gui_sprite_t spr24_osc_vosim;
extern const gui_sprite_t spr24_osc_vowel;
extern const gui_sprite_t spr24_osc_wline;
extern const gui_sprite_t spr24_osc_wmap;
extern const gui_sprite_t spr24_osc_wtbl;
extern const gui_sprite_t spr24_osc_zbp;
extern const gui_sprite_t spr24_osc_zhp;
extern const gui_sprite_t spr24_osc_zlp;
extern const gui_sprite_t spr24_osc_zpk;
extern const gui_sprite_t spr24_slot_empty;
extern const gui_sprite_t spr24_slot_out;

// The sprite of an image by its path without .png and frame number ("24/mod_osc"); NULL when there is no such image (the caller then
// draws its own fallback, so the art can arrive one file at a time).
const gui_sprite_t *ui_sprite(const char *name);

#ifdef __cplusplus
}
#endif
