// GENERATED by tools/gen_ui_sprites.py from assets/UI_Sprites/ -- do not edit by hand.
#include "core/ui_sprites_gen.h"
#include <string.h>

static const uint8_t spr8_ui_xy_data[8] = {
    0x00, 0xAA, 0xAA, 0x44, 0xA4, 0xA4, 0x00, 0x00
};
static const uint8_t spr8_ui_xy_mask[8] = {
    0x00, 0xAA, 0xAA, 0x44, 0xA4, 0xA4, 0x00, 0x00
};
const gui_sprite_t spr8_ui_xy = {8, 8, spr8_ui_xy_data, 1, spr8_ui_xy_mask};

static const struct { const char *name; const gui_sprite_t *sp; } table[] = {
    {"8/ui_xy", &spr8_ui_xy},
};

const gui_sprite_t *ui_sprite(const char *name) {
    for (size_t i = 0; i < sizeof table / sizeof table[0]; i++) if (table[i].name && !strcmp(table[i].name, name)) return table[i].sp;
    return NULL;
}
