#!/usr/bin/env python3
"""Generates src/engine/dsp/wavetables.cpp: band-limited (mipmap) single-cycle tables for the Strings oscillators (ADR-037).

  kMipSaw[kMipBands][1025]  rising saw, band k holds the harmonics 1 .. kMipHarm(k) (511, 256, 128, ... 1), +1 guard entry
  kMipTri[kMipBands][1025]  triangle (odd harmonics, 1/n^2, alternating sign), same bands

Band k is used while (512 >> k) * f0 stays below half the sample rate (see wavetables.h), so the highest harmonic of a table never aliases.
Every band of a wave is scaled by the same factor (the peak of its fullest band, Gibbs overshoot included) so the level does not jump between bands.
Pulse waves are the difference of two saw reads (no table of their own).

Run:  python tools/gen_wavetables.py      (the generated file is committed)
"""
import math
import os

N = 1024          # samples per cycle (the highest harmonic a table can hold is N / 2 - 1 = 511)
BANDS = 10        # 511, 256, 128, 64, 32, 16, 8, 4, 2, 1 harmonics
PEAK = 0.95       # full scale of the loudest table

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out = os.path.join(root, "src", "engine", "dsp", "wavetables.cpp")
sin_tab = [math.sin(2 * math.pi * i / N) for i in range(N)]


def harm(k):
    return min(N // 2 - 1, (N // 2) >> k)


def build(coef):
    """coef(n) -> amplitude of harmonic n (sine phase). Returns BANDS float tables of N samples."""
    tabs = []
    for k in range(BANDS):
        h = harm(k)
        t = [0.0] * N
        for n in range(1, h + 1):
            a = coef(n)
            if a == 0.0:
                continue
            for i in range(N):
                t[i] += a * sin_tab[(n * i) % N]
        tabs.append(t)
    return tabs


def saw_coef(n):          # rising saw x / pi on (-pi, pi): 2/pi * sum (-1)^(n+1) sin(n x) / n
    return 2.0 / math.pi * ((-1) ** (n + 1)) / n


def tri_coef(n):          # triangle: 8/pi^2 * sum over odd n of (-1)^((n-1)/2) sin(n x) / n^2
    if n % 2 == 0:
        return 0.0
    return 8.0 / (math.pi ** 2) * ((-1) ** ((n - 1) // 2)) / (n * n)


def emit(name, tabs, lines):
    peak = max(abs(v) for t in tabs for v in t)
    scale = PEAK * 32767.0 / peak
    lines.append("WT_TABLE const int16_t %s[kMipBands][kMipSize + 1] = {" % name)
    for t in tabs:
        vals = [max(-32767, min(32767, round(v * scale))) for v in t]
        vals.append(vals[0])                              # guard: linear interpolation reads idx + 1
        lines.append("    {")
        for i in range(0, len(vals), 16):
            lines.append("        " + ", ".join(str(v) for v in vals[i:i + 16]) + ",")
        lines.append("    },")
    lines.append("};")
    lines.append("")


# Phase convention (the same as the naive saw, int32(phase) >> 16): phase 0 = value 0 rising, the reset (+1 -> -1) at half a cycle.
lines = [
    "// GENERATED by tools/gen_wavetables.py - do not edit.",
    '#include "engine/dsp/wavetables.h"',
    "",
    "namespace sc {",
    "",
]
emit("kMipSaw", build(saw_coef), lines)
emit("kMipTri", build(tri_coef), lines)
lines.append("}  // namespace sc")
lines.append("")
with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))
print("wrote", out)
