"""Generates src/core/module_sprites.h: one 24x24 rounded-square sprite per module type
with a 2-letter code inside, plus an empty-slot sprite and an OUT arrow.

Run from oled_sim:   python tools/gen_module_sprites.py
Format: 24 px wide -> 3 bytes per row (MSB = leftmost pixel), 24 rows (the 24 px icon size of assets/UI_Sprites/README.md). The size is the one place to change (W, H);
ui_internal.h has RACK_PITCH = sprite width + 4 and ui_draw / scr_rack.c check it.
To add a module: add (name, code) to MODULES (order must match module_type_t in rack.h),
add missing letters to GLYPHS, run the script.
"""
import os

W = H = 24
ROWB = (W + 7) // 8      # bytes per row
MODULES = [("osc", "OC"), ("filter", "FL"), ("sat", "SA"), ("lfo", "LF"), ("mseq", "MS"), ("env", "EN"), ("sampler", "SM"), ("eg", "EG"), ("comb", "RS")]

# 5x7 glyphs, '#' = pixel on
GLYPHS = {
    "O": [".###.", "#...#", "#...#", "#...#", "#...#", "#...#", ".###."],
    "C": [".###.", "#...#", "#....", "#....", "#....", "#...#", ".###."],
    "F": ["#####", "#....", "#....", "####.", "#....", "#....", "#...."],
    "L": ["#....", "#....", "#....", "#....", "#....", "#....", "#####"],
    "S": [".####", "#....", "#....", ".###.", "....#", "....#", "####."],
    "A": [".###.", "#...#", "#...#", "#####", "#...#", "#...#", "#...#"],
    "M": ["#...#", "##.##", "#.#.#", "#.#.#", "#...#", "#...#", "#...#"],
    "E": ["#####", "#....", "#....", "####.", "#....", "#....", "#####"],
    "N": ["#...#", "##..#", "#.#.#", "#..##", "#...#", "#...#", "#...#"],
    "G": [".###.", "#...#", "#....", "#.###", "#...#", "#...#", ".###."],
    "R": ["####.", "#...#", "#...#", "####.", "#.#..", "#..#.", "#...#"],
}


def blank():
    return [[0] * W for _ in range(H)]


def frame(px, dashed=False):
    for i in range(1, W - 1):
        for (x, y) in ((i, 0), (i, H - 1), (0, i), (W - 1, i)):
            if not dashed or i % 2 == 1:
                px[y][x] = 1


def put_glyph(px, ch, x0, y0, scale=2):
    for r, row in enumerate(GLYPHS[ch]):
        for c, v in enumerate(row):
            if v == "#":
                for dy in range(scale):
                    for dx in range(scale):
                        px[y0 + r * scale + dy][x0 + c * scale + dx] = 1


def module_sprite(code):
    px = blank()
    frame(px)
    put_glyph(px, code[0], 2, (H - 14) // 2)
    put_glyph(px, code[1], 12, (H - 14) // 2)
    return px


def empty_sprite():
    px = blank()
    frame(px, dashed=True)
    for i in range(9, 16):
        px[12][i] = 1
        px[i][12] = 1
    return px


def out_sprite():
    px = blank()
    for x in range(3, 14):
        px[12][x] = 1
        px[11][x] = 1
    for r in range(-7, 8):
        for x in range(13, 22 - abs(r)):
            px[12 + r][x] = 1
    return px


def emit(name, px):
    lines = []
    art = []
    for row in px:
        bits = "".join("1" if v else "0" for v in row).ljust(ROWB * 8, "0")
        lines.append(", ".join("0x%02X" % int(bits[i * 8:(i + 1) * 8], 2) for i in range(ROWB)))
        art.append("".join("X" if v else "." for v in row))
    out = "static const uint8_t spr_%s_data[%d * %d] = {\n" % (name, H, ROWB)
    for l, a in zip(lines, art):
        out += "    %s,   // %s\n" % (l, a)
    out += "};\nstatic const gui_sprite_t spr_%s = {%d, %d, spr_%s_data, 1};\n\n" % (name, W, H, name)
    return out


def main():
    text = ("#pragma once\n// GENERATED by tools/gen_module_sprites.py -- do not edit by hand.\n"
            "// The fallback when assets/UI_Sprites/24/ has no image for a module (scr_rack.c: module_sprite).\n"
            "// %dx%d module sprites (rounded square + 2-letter code), empty slot and OUT arrow.\n" % (W, H) +
            "#define MODULE_SPRITE_W %d\n#define MODULE_SPRITE_H %d\n" % (W, H) +
            "#include \"core/gui.h\"\n\n")
    for name, code in MODULES:
        text += emit("mod_" + name, module_sprite(code))
    text += emit("slot_empty", empty_sprite())
    text += emit("slot_out", out_sprite())
    path = os.path.join(os.path.dirname(__file__), "..", "src", "core", "module_sprites.h")
    with open(path, "w") as f:
        f.write(text.rstrip() + "\n")
    print("wrote", os.path.normpath(path))


main()
