"""Generates the DX7 data used by the FM editor from AMY's sources:

  src/core/dx7_factory.c   the 128 DX7 patches (AMY patch numbers 128..255) as editable parameters
  src/core/dx7_algos.c     one 61x49 diagram sprite per algorithm (+ operator box positions)

Run from oled_sim:   python tools/gen_dx7.py
Inputs: lib/amy/src/patches.h (patch strings) and lib/amy/src/algorithms.c (operator wiring).
"""
import math, os, re

ROOT = os.path.join(os.path.dirname(__file__), "..")
AMY = os.path.join(ROOT, "lib", "amy", "src")
OUT = os.path.join(ROOT, "src", "core")

# ------------------------------------------------------------------ factory patches
def level_from_amp(a):        # amp = 2 * 2^((L-99)/8)
    return 0 if a <= 0 else max(0, min(99, round(99 + 8 * math.log2(a / 2.0))))

def level_from_env(v):        # env value = 2^((L-99)/8)
    return 0 if v <= 0 else max(0, min(99, round(99 + 8 * math.log2(v))))

def parse_patch(msg):
    patch = {"algo": 1, "fb": 0.0, "rel": 731, "ops": {}}
    for part in msg.split("Z"):
        if not part:
            continue
        toks = re.findall(r"([A-Za-z])([-0-9.,]*)", part)
        if not toks or toks[0][0] != "v":
            continue
        osc = int(toks[0][1])
        d = {}
        for letter, val in toks[1:]:
            d[letter] = val
        if osc == 0:
            patch["algo"] = int(d.get("o", "1"))
            patch["fb"] = float(d.get("b", "0") or 0)
            if "A" in d:
                nums = [float(x) for x in d["A"].split(",") if x != ""]
                if len(nums) >= 2:
                    patch["rel"] = int(nums[-2])
        elif 2 <= osc <= 7:
            op = 8 - osc                      # osc 7 = operator 1 ... osc 2 = operator 6
            level = level_from_amp(float(d["a"].split(",")[0])) if "a" in d else 99
            nums = [float(x) for x in d.get("A", "").split(",") if x != ""]
            pairs = list(zip(nums[0::2], nums[1::2]))
            if len(pairs) == 5:               # (0,L4), (t1,L1), (t2,L2), (t3,L3), (t4,L4)
                t = [int(pairs[i][0]) for i in (1, 2, 3, 4)]
                l = [level_from_env(pairs[i][1]) for i in (1, 2, 3, 4)]
            else:                             # unexpected shape: flat envelope
                t, l = [0, 0, 0, 100], [99, 99, 99, 0]
            ratio, fixed = 1.0, 0.0
            if "I" in d:
                ratio = float(d["I"])
            elif "f" in d:
                fixed = float(d["f"].split(",")[0])
            coarse = max(0.5, round(ratio * 2) / 2.0)
            patch["ops"][op] = (level, coarse, ratio - coarse if not fixed else 0.0, fixed, l, t)
    return patch

def gen_factory():
    src = open(os.path.join(AMY, "patches.h"), encoding="utf-8").read()
    entries = re.findall(r'/\*\s*(\d+):\s*([^*]*?)\s*\*/\s*"([^"]*)"', src)
    byn = {int(n): (name, msg) for n, name, msg in entries}
    out = ['// GENERATED by tools/gen_dx7.py from AMY patches.h -- do not edit by hand.\n',
           '#include "core/dx7.h"\n\n',
           'const dx7_patch_t dx7_factory[DX7_FACTORY_COUNT] = {\n']
    for i in range(128):
        name, msg = byn[128 + i]
        name = re.sub(r"\s+", " ", name.replace("DX7 ", "", 1)).strip()[:11]
        p = parse_patch(msg)
        ops = []
        for op in range(1, 7):
            level, coarse, fine, fixed, l, t = p["ops"].get(op, (0, 1.0, 0.0, 0.0, [99, 99, 99, 0], [0, 0, 0, 100]))
            ops.append("{%d, %.1ff, %.5ff, %.4ff, {%d, %d, %d, %d}, {%d, %d, %d, %d}}"
                       % (level, coarse, fine, fixed, *l, *t))
        out.append('    {"%s", %d, %.4ff, %d, {\n        %s\n    }},   /* %d */\n'
                   % (name, p["algo"], p["fb"], p["rel"], ",\n        ".join(ops), i + 1))
    out.append('};\n')
    open(os.path.join(OUT, "dx7_factory.c"), "w").write("".join(out))

# ------------------------------------------------------------------ algorithm diagrams
W, H = 61, 49
BOX, GAPY = 9, 4

DIGITS = {
    "1": ["010", "110", "010", "010", "111"], "2": ["110", "001", "010", "100", "111"],
    "3": ["110", "001", "010", "001", "110"], "4": ["101", "101", "111", "001", "001"],
    "5": ["111", "100", "110", "001", "110"], "6": ["011", "100", "110", "101", "010"],
}

def parse_algorithms():
    src = open(os.path.join(AMY, "algorithms.c")).read()
    rows = re.findall(r"\{\s*\{\s*((?:0x[0-9a-fA-F]+\s*,?\s*){6})\}\s*\},\s*//\s*(\d+)", src)
    algos = {}
    for vals, n in rows:
        algos[int(n)] = [int(v, 16) for v in re.findall(r"0x[0-9a-fA-F]+", vals)]
    return algos

def topology(flags):
    """flags[0..5] describe op6..op1. Returns (edges, carriers, fb_op)."""
    bus = {1: set(), 2: set()}
    edges, carriers, fb_in, fb_out = [], [], None, None
    for i, f in enumerate(flags):
        op = 6 - i
        inb, outb, add = (f >> 4) & 3, f & 3, f & 4
        if inb:
            for s in bus[inb]:
                edges.append((s, op))
        if f & 0x40: fb_in = op
        if f & 0x80: fb_out = op
        if outb == 0:
            carriers.append(op)
        elif add:
            bus[outb].add(op)
        else:
            bus[outb] = {op}
    return edges, carriers, fb_in, fb_out

def layout(edges, carriers):
    depth = {c: 0 for c in carriers}
    changed = True
    while changed:
        changed = False
        for s, t in edges:
            if t in depth and depth.get(s, -1) < depth[t] + 1:
                depth[s] = depth[t] + 1
                changed = True
    layers = {}
    for op in range(1, 7):
        layers.setdefault(depth.get(op, 0), []).append(op)
    nl = max(layers) + 1
    pos = {}
    for d, ops in layers.items():
        ops.sort(reverse=True)
        n = len(ops)
        step = min(BOX + 3, (W - BOX) // max(1, n - 1)) if n > 1 else 0
        total = BOX + step * (n - 1)
        x0 = (W - total) // 2
        y = (nl - 1 - d) * (BOX + GAPY) + (H - (nl * BOX + (nl - 1) * GAPY)) // 2
        for k, op in enumerate(ops):
            pos[op] = (x0 + k * step, y)
    return pos

def render(edges, carriers, fb_in, fb_out, pos):
    px = [[0] * W for _ in range(H)]
    def line(x0, y0, x1, y1):
        n = max(abs(x1 - x0), abs(y1 - y0), 1)
        for k in range(n + 1):
            x, y = x0 + (x1 - x0) * k // n, y0 + (y1 - y0) * k // n
            if 0 <= x < W and 0 <= y < H: px[y][x] = 1
    for s, t in edges:                              # modulator (above) -> target: bottom centre to top centre
        sx, sy = pos[s]; tx, ty = pos[t]
        line(sx + BOX // 2, sy + BOX, tx + BOX // 2, ty - 1)
    for c in carriers:                              # carriers: short stub to the output line
        cx, cy = pos[c]
        line(cx + BOX // 2, cy + BOX, cx + BOX // 2, min(H - 1, cy + BOX + 2))
    for op, (x, y) in pos.items():
        for i in range(BOX):
            for j in range(BOX):
                edge = i in (0, BOX - 1) or j in (0, BOX - 1)
                corner = i in (0, BOX - 1) and j in (0, BOX - 1)
                px[y + i][x + j] = 1 if edge and not corner else 0
        g = DIGITS[str(op)]
        for r, row in enumerate(g):
            for c, v in enumerate(row):
                if v == "1": px[y + 2 + r][x + 3 + c] = 1
    if fb_in is not None:                           # feedback: hook on the right side of the op (or loop to fb_out)
        x, y = pos[fb_in]
        line(x + BOX, y + 2, x + BOX + 2, y + 2)
        line(x + BOX + 2, y + 2, x + BOX + 2, y + BOX - 3)
        line(x + BOX + 2, y + BOX - 3, x + BOX, y + BOX - 3)
        if fb_out is not None and fb_out != fb_in:
            ox, oy = pos[fb_out]
            line(ox + BOX, oy + BOX // 2, x + BOX + 2, y + BOX - 3)
    return px

def gen_algos():
    algos = parse_algorithms()
    out = ['// GENERATED by tools/gen_dx7.py from AMY algorithms.c -- do not edit by hand.\n',
           '// One %dx%d diagram per DX7 algorithm (8 bytes per row, MSB = leftmost pixel) and the position of each operator box.\n'
           % (W, H), '#include "core/dx7_algos.h"\n\n']
    for a in range(1, 33):
        edges, carriers, fb_in, fb_out = topology(algos[a])
        pos = layout(edges, carriers)
        px = render(edges, carriers, fb_in, fb_out, pos)
        out.append("static const uint8_t algo%d_bits[%d * 8] = {\n" % (a, H))
        for row in px:
            bits = "".join(map(str, row)) + "0" * (64 - W)
            out.append("    " + ", ".join("0x%02X" % int(bits[i:i + 8], 2) for i in range(0, 64, 8)) + ",\n")
        out.append("};\n")
    out.append("\nconst dx7_algo_gfx_t dx7_algo_gfx[DX7_ALGORITHMS] = {\n")
    for a in range(1, 33):
        edges, carriers, fb_in, fb_out = topology(algos[a])
        pos = layout(edges, carriers)
        xs = ", ".join(str(pos[op][0]) for op in range(1, 7))
        ys = ", ".join(str(pos[op][1]) for op in range(1, 7))
        out.append("    {algo%d_bits, {%s}, {%s}},\n" % (a, xs, ys))
    out.append("};\n")
    open(os.path.join(OUT, "dx7_algos.c"), "w").write("".join(out))
    depth = max(len(set(pos_y)) for pos_y in [[layout(*topology(algos[a])[:2])[op][1] for op in range(1, 7)] for a in range(1, 33)])
    print("algorithm layers max:", depth)

gen_factory()
gen_algos()
print("ok")
