#pragma once
// Band-limited single-cycle tables (mipmaps) for the Strings oscillators (ADR-037). Generated by tools/gen_wavetables.py.
// Band k holds the harmonics 1 .. kMipHarm(k) = 511, 256, 128, ... 1. An oscillator with phase increment `inc` (2^32 = one cycle per sample)
// uses the first band whose highest harmonic stays below half the sample rate: (512 >> k) * inc < 2^31. The level is the same in every band.
// Phase convention as the naive saw (int32(phase) >> 16): phase 0 = value 0 rising, the reset at half a cycle.
//
// Memory: 2 waves x 10 bands x 1025 x 2 bytes = 41 KB. In flash by default (a read that misses the cache costs ~120 cycles on the ESP32-S3,
// see tables.h); -DENGINE_WT_RAM=1 puts them in internal RAM (fast, but 41 KB less for the engine's fast heap).
#include <cstdint>

#if defined(ARDUINO_ARCH_ESP32) && defined(ENGINE_WT_RAM) && ENGINE_WT_RAM
#include <esp_attr.h>
#define WT_TABLE DRAM_ATTR
#else
#define WT_TABLE
#endif

namespace sc {

constexpr int kMipBits = 10;
constexpr int kMipSize = 1 << kMipBits;             // samples per cycle
constexpr int kMipBands = 10;
extern const int16_t kMipSaw[kMipBands][kMipSize + 1];
extern const int16_t kMipTri[kMipBands][kMipSize + 1];

// The band for a phase increment: the first k with (512 >> k) * inc < 2^31.
inline int mip_band(uint32_t inc) {
    int k = 0;
    while (k < kMipBands - 1 && (static_cast<uint64_t>(512u >> k) * inc) >= 0x80000000ull) k++;
    return k;
}

// Linear interpolation in one band; phase as an unsigned 32-bit cycle.
inline int32_t mip_read(const int16_t *t, uint32_t ph) {
    const uint32_t i = ph >> (32 - kMipBits);
    const int32_t frac = static_cast<int32_t>((ph >> (32 - kMipBits - 15)) & 0x7fff);    // q15
    const int32_t a = t[i], b = t[i + 1];
    return a + (((b - a) * frac) >> 15);
}

}  // namespace sc
