#pragma once
// Band-limited single-cycle tables (mipmaps) for the Strings oscillators (ADR-037). Generated by tools/gen_wavetables.py.
// Band k holds the harmonics 1 .. kMipHarm(k) = 511, 256, 128, ... 1. An oscillator with phase increment `inc` (2^32 = one cycle per sample)
// uses the first band whose highest harmonic stays below half the sample rate: (512 >> k) * inc < 2^31. The level is the same in every band.
// Phase convention as the naive saw (int32(phase) >> 16): phase 0 = value 0 rising, the reset at half a cycle.
//
// Memory: 2 waves x 10 bands x 1025 x 2 bytes = 41 KB. In flash by default (a read that misses the cache costs ~120 cycles on the ESP32-S3,
// see tables.h); -DENGINE_WT_RAM=1 puts them in internal RAM (fast, but 41 KB less for the engine's fast heap).
#include <cstdint>

#if defined(ARDUINO_ARCH_ESP32) && defined(ENGINE_WT_RAM) && ENGINE_WT_RAM
#include <esp_attr.h>
#define WT_TABLE DRAM_ATTR
#else
#define WT_TABLE
#endif

namespace sc {

constexpr int kMipBits = 10;
constexpr int kMipSize = 1 << kMipBits;             // samples per cycle
constexpr int kMipBands = 10;
extern const int16_t kMipSaw[kMipBands][kMipSize + 1];
extern const int16_t kMipTri[kMipBands][kMipSize + 1];

// The band for a phase increment: the first k with (512 >> k) * inc < 2^31.
inline int mip_band(uint32_t inc) {
    int k = 0;
    while (k < kMipBands - 1 && (static_cast<uint64_t>(512u >> k) * inc) >= 0x80000000ull) k++;
    return k;
}

// Linear interpolation in one band; phase as an unsigned 32-bit cycle.
inline int32_t mip_read(const int16_t *t, uint32_t ph) {
    const uint32_t i = ph >> (32 - kMipBits);
    const int32_t frac = static_cast<int32_t>((ph >> (32 - kMipBits - 15)) & 0x7fff);    // q15
    const int32_t a = t[i], b = t[i + 1];
    return a + (((b - a) * frac) >> 15);
}

// The table oscillator shared by the Strings voice, the Strings engine of the rack oscillator and the plain Osc waves in "Mip" / "Naive" quality.
// W: WT_SAW (rising), WT_PULSE (the difference of two saws `pw_off` apart, same level), WT_TRI. Mip = the band-limited table `tab`
// (wt_table), else the naive phase accumulator (`tab` unused). Output about +-0.95 full scale.
enum WtWave { WT_SAW, WT_PULSE, WT_TRI, WT_WAVES };

inline const int16_t *wt_table(int wave, uint32_t inc) { return wave == WT_TRI ? kMipTri[mip_band(inc)] : kMipSaw[mip_band(inc)]; }

template <int W, bool Mip>
inline int32_t wt_osc(uint32_t ph, uint32_t pw_off, const int16_t *tab) {
    if (Mip) {
        if (W == WT_TRI) return mip_read(tab, ph);
        const int32_t a = mip_read(tab, ph);
        if (W == WT_SAW) return a;
        return (a - mip_read(tab, ph + pw_off)) >> 1;
    }
    if (W == WT_TRI) {                                                     // |saw| folded: -1 at phase 0, +1 at half a cycle (-32768 .. 32766)
        const int32_t s = static_cast<int32_t>(ph) >> 16;
        return ((s ^ (s >> 31)) - 16384) * 2;
    }
    const int32_t a = static_cast<int32_t>(ph) >> 16;
    if (W == WT_SAW) return a;
    return (a - (static_cast<int32_t>(ph + pw_off) >> 16)) >> 1;
}

// Runtime choice of the same (for loops that already branch per sample).
inline int32_t wt_osc_any(int wave, bool mip, uint32_t ph, uint32_t pw_off, const int16_t *tab) {
    switch (wave) {
        case WT_PULSE: return mip ? wt_osc<WT_PULSE, true>(ph, pw_off, tab) : wt_osc<WT_PULSE, false>(ph, pw_off, tab);
        case WT_TRI:   return mip ? wt_osc<WT_TRI, true>(ph, pw_off, tab) : wt_osc<WT_TRI, false>(ph, pw_off, tab);
        default:       return mip ? wt_osc<WT_SAW, true>(ph, pw_off, tab) : wt_osc<WT_SAW, false>(ph, pw_off, tab);
    }
}

}  // namespace sc
